### ISSUE TITLE
no data to use

### ISSUE THREAD

**Issue by lhyxyw** [foneafone/PyPhasePick#1]
Sir, there is no data in your code package ,so the absolute path in the codes can not to use

**Comment by foneafone** [comment]
The data is on my computer as this isn't realy tested for other people to use, mainly just a backup and version control repo for my own work. You're welcome to try and use it but you'll need your own data and to edit the paths, it is set up to work on cross correlations output from msnoise (http://www.msnoise.org/) so I'd recomend starting there.
